# TechX - Machine Learning Course 

## Assignment 1 - Python and NumPy

This is an introductory assignment to the course. Two fundamental skills that every data scientist must have are math and python. Make sure that you are able to do all of the following questions. If you have trouble, please make sure to ask for help from either the ALs or the mentors. 

In [2]:
def test_function(function, test_cases, test_cases_answers):
    """Runs function through test cases"""
    passed = True
    
    for (case, answer) in zip(test_cases, test_cases_answers):
        output = function(case)
        if output != answer: 
            print('Your output: ', output, '\t Expected output: ', answer)
            passed = False
    
    if passed: 
        print('Test passed.')
    else: 
        print('Test failed.')

## Functions

###### 1) Write a function that calculates the average of an array in an iterative way

In [4]:
def average(array):
    """ Calculates the average of array. Returns average float"""
    sum=0;
    for item in array:
        sum+=item;
    return sum/len(array)
    #=============== YOUR CODE HERE ===================

Run the next cell to test your function.

In [5]:
test_cases_average = [[1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [0.21780088, 0.4118428,  0.62573827, 0.78184048, 0.96162729, 0.21242742, 0.06843751, 0.70688805, 0.98459559, 0.1153083 ]]

test_cases_answers_average = [1, 5.5, 0.508650659]

test_function(average, test_cases_average, test_cases_answers_average)

Test passed.


### Indexing, Slicing and Iterating

###### 2) Extract the username of these emails. Beware, there may be different domains! You want to return the String before '@'.

Example: <br>
<b>input:</b> 'john.smith@qq.com' <br>
<b>return:</b>'john.smith'

<b>input:</b> 'jennifer@outlook.com' <br>
<b>return:</b>'jennifer' 

In [8]:
def extract_username(email): 
    """Extracts the username from the input email address. Return username String"""
    username=email.split('@')[0]
    return username
    #=============== YOUR CODE HERE ===================

Run the next cell to test your function.

In [9]:
test_cases_extract_username = ['john-smith@gmail.com',
              'this.is.the.username@abcdefghijklmnopqrstuvwxyz',
              'invalid-email']

test_cases_answers_extract_username = ['john-smith', 'this.is.the.username', 'invalid-email']

test_function(extract_username, test_cases_extract_username, test_cases_answers_extract_username) 

Test passed.


<hr>

### Complete the following questions using ONLY NumPy

### Linear algebra operations 

###### 3) Import NumPy Library into your Python environment

In [2]:
#=============== YOUR CODE HERE ===================
import numpy as np

###### 4) Create a 10 element vector, x, of random integers between 10 and 15 (inclusive).  

In [20]:
x = np.random.randint(10, 16, 10)# YOUR CODE HERE
print(x)
max=np.max(x)
print(max)
max_index=np.argmax(x)
print(max_index)

[14 10 12 13 12 14 10 10 11 13]
14
0


###### q) Print out the max value of the array. 

###### q) Print out the position of the max value of the array. 

###### 5) Create a 10 element vector, y, of 1.  

In [21]:
y = np.ones(10,dtype = int)# YOUR CODE HERE
print(y)

[1 1 1 1 1 1 1 1 1 1]


###### 6) Add x and y together

In [22]:
answer = x+y# YOUR CODE HERE
print(answer)

[15 11 13 14 13 15 11 11 12 14]


###### 7) Convert the following matrix into a numpy array. 

$\begin{bmatrix}
5 & 10 & 15\\ 
2 &  13 & 23
\end{bmatrix}$

In [4]:
matrix = np.array([[5,10,15],[2,13,23]])# YOUR CODE HERE

print(matrix)

[[ 5 10 15]
 [ 2 13 23]]


###### 8) Transpose the matrix. You should get 

$\begin{bmatrix}
5 & 2 \\
10 & 13 \\
15 & 23 \\
\end{bmatrix}$

In [5]:
matrix_T = matrix.T# YOUR CODE HERE
print(matrix_T)

[[ 5  2]
 [10 13]
 [15 23]]


###### 9) Multiply matrix and matrix_T together. You should get 

$\begin{bmatrix}
350 & 485 \\
485 & 702 
\end{bmatrix}$

In [6]:
matrix_square = np.matmul(matrix,matrix_T)# YOUR CODE HERE
print(matrix_square)

[[350 485]
 [485 702]]


###### q) Print out the determinant of the squared matrix. 

In [31]:
det = np.linalg.det(matrix_square)# YOUR CODE HERE
print(det)

10474.99999999999


###### q) Print out the inverse matrix. 

In [32]:
inv = np.linalg.inv(matrix_square)# YOUR CODE HERE
print(inv)

[[ 0.06701671 -0.04630072]
 [-0.04630072  0.03341289]]


###### q) Print out the eigenvectors and the eigenvalues of the squared matrix. 

In [8]:
eigenvalues ,eigenvectors = np.linalg.eig(matrix_square)# YOUR CODE HERE
print('eigenvalues: ', eigenvalues)
print('eigenvectors: ', eigenvectors)

eigenvalues:  [  10.05329733 1041.94670267]
eigenvectors:  [[-0.81887743 -0.57396842]
 [ 0.57396842 -0.81887743]]


###### q) Check if the eigen properties hold true. 

Remember that the linear transformation by a matrix on its eigenvectors does not change the direction of the vector, only their lenghts. Eigenvalues are the scalars used to 'stretch' the eigenvectors during the transformation. 

$ Av = \lambda v $ 

In [10]:
#=============== YOUR CODE HERE ===================
for i in range(2):
    val1=np.dot(matrix_square[:,:], eigenvectors[:,i])
    print(matrix_square[:, :], eigenvectors[:,i])
    val2=eigenvalues[i] * eigenvectors[:,i]
    if np.all([val1,val2]):
        print('ok for ', i)
    else:
        print('no')
    print(val1,val2)

[[350 485]
 [485 702]] [-0.81887743  0.57396842]
ok for  0
[-8.23241832  5.77027518] [-8.23241832  5.77027518]
[[350 485]
 [485 702]] [-0.57396842 -0.81887743]
ok for  1
[-598.04450277 -853.22664277] [-598.04450277 -853.22664277]


###### 10) Create a 3-element vector with integers of your choice. 

In [75]:
v = np.array([1,2,3])# YOUR CODE HERE
print(v)

[1 2 3]


###### 11) Multiply matrix and v. 
Be careful, you want to make sure that the dimensions of the two arrays match up. Your vector should therefore be a (3, 1) matrix. Use the <b>shape<b> to see what dimension is <emph>v<emph> and <b>reshape<b> as needed. 

In [80]:
#=============== YOUR CODE HERE ===================
if v.shape!=(3,1):
    v=v.reshape(3,1)
print(v)
answer=np.matmul(matrix,v)
print(answer)

[[1]
 [2]
 [3]]
[[70]
 [97]]


###### 12) Flatten matrix into a 6-element vector. 

In [85]:
flatten = matrix.flatten() # YOUR CODE HERE 
print(flatten)

[ 5 10 15  2 13 23]


###### 13) Concatenate the following matrices.

*Note: Don't forget to convert the matrices to numpy arrays first.*

In [86]:
matrix1 = [[1, 2, 3, 4, 5], 
           [6, 7, 8, 9, 10], 
           [11, 12, 13, 14, 15]]

matrix2 = [[16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]]

a) along axis 0. 
You should get 

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 \\
 6 & 7 & 8 & 9 & 10 \\
 11 & 12 & 13 & 14 & 15 \\
 16 & 17 & 18 & 19 & 20 \\
 21 & 22 & 23 & 24 & 25 \\
 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [87]:
answer = np.array(matrix1+matrix2)# YOUR CODE HERE 

print(answer)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


b) along axis 1. You should get

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 & 16 & 17 & 18 & 19 & 20 \\
 6 & 7 & 8 & 9 & 10 & 21 & 22 & 23 & 24 & 25 \\
 11 & 12 & 13 & 14 & 15 & 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [89]:
answer = np.array([matrix1[i]+matrix2[i] for i in range(3)])# YOUR CODE HERE 

print(answer)

[[ 1  2  3  4  5 16 17 18 19 20]
 [ 6  7  8  9 10 21 22 23 24 25]
 [11 12 13 14 15 26 27 28 29 30]]


### Basic statistics 

###### Create a vector $v$ with 30 random integers from 1 to 20. 

In [90]:
v = np.random.randint(1,21,30)# YOUR CODE HERE 
print(v)

[ 2 16 20 14  4  4  7 18  8 18 11  8  9  6  5  6 17 17  7 10 12 20  8 11
 18 11  7  5  4 17]


###### Print out the median of the list $ v $.

In [91]:
median = np.median(v)# YOUR CODE HERE 
print(median)

9.5


###### Print out the standard deviation of $ v$.

In [92]:
std = np.std(v)# YOUR CODE HERE
print(std)

5.411920998027307


###### q) Randomly sample 5 items from the following list.

In [93]:
list = np.arange(10) 
print(list)

[0 1 2 3 4 5 6 7 8 9]


In [97]:
sample = np.random.choice(list,5)# YOUR CODE HERE 
print(sample)

[4 2 5 4 6]


###### q) Now sample 5 items again from the list, but this time without replacement. 
If you are sampling with replacement, after each sampling, the item you chose is put into the pool and can be chosen again in following samplings. Whereas, the items are removed from the pool and will not be available again if you are not sampling with replacement. 

In [99]:
sample = np.random.choice(list,5,False)# YOUR CODE HERE 
print(sample)

[5 0 1 8 6]


### Now it is time for a (small) challenge 

###### Maximum A Posteriori 
At a very high level, in Bayesian statistics, MAP is an estimate of an unknown quantity that takes into considerations prior assumptions and past events. 
For example, in a coin toss, the theoretical assumption is 0.5 probability of face and tail. However, the probability distribution will change based on the previous results of the coin toss.

Let $x$ be the random variable of the coin toss, with $x$ = 1 being Head and $x$ = 0 Tail. Let $\theta$ be the probability of getting 1. Intuitively, suppose you get 3 heads out of 10 tosses, your $\theta$ value would be $\theta = \frac{head}{total} = \frac{3}{10} = 0.3$.


We can model the coin toss with a Bernouilli equation. 
$\theta = P(x = 1) = 1 - P(x = 0)$. 

The probability mass function of $x$ depending on $\theta$ is then $P(x | \theta) = \theta^x (1 - \theta)^{1-x}$, where $\theta$ is defined by prior data and updated after each iteration. 



The formula to estimate the probability is $ \hat{\theta}_{MAP}(x) = \underset{\theta}{\mathrm{argmin}} P(x | \theta) P(\theta)$

You can read more about MAP here: https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/


###### Given this, code out a formula that estimates the probability of a BIASED coin landing on HEAD after 20 tosses. 

Assume that you did not know that coin was biased at the beginning, so start with a $P(x = 1) = 0.5$. 
Toss your coin with a bias of $P(x = 1) = 0.8$. After each iteration, print out the total number of Tails and Heads you have gotten, and the updated $\theta$. 

What do you observe? 



In [14]:
#=============== YOUR CODE HERE ===================
#With alpha=beta=2
import random
def theta(head, total):
    return ((2+head-1)/(2+total)) #2+2+heads+tails-2=2+total

def main():
    head=0
    proba=[0,0,1,1,1,1,1,1,1,1] #0.8 theorical probability to get a head
    for i in range(20):
        res=proba[random.randint(0,9)]
        if res==1:
            head+=1
        theta_now=theta(head,i+1)
        print('Toss no %d \n Heads: %d, Tails %d, Theta MAP: %lf' %(i+1, head, i+1-head, theta_now))
if __name__=='__main__':
    main()
    
#I observe that the MAP approaches 0.8. 

Toss no 1 
 Heads: 1, Tails 0, Theta MAP: 0.666667
Toss no 2 
 Heads: 1, Tails 1, Theta MAP: 0.500000
Toss no 3 
 Heads: 2, Tails 1, Theta MAP: 0.600000
Toss no 4 
 Heads: 3, Tails 1, Theta MAP: 0.666667
Toss no 5 
 Heads: 4, Tails 1, Theta MAP: 0.714286
Toss no 6 
 Heads: 4, Tails 2, Theta MAP: 0.625000
Toss no 7 
 Heads: 5, Tails 2, Theta MAP: 0.666667
Toss no 8 
 Heads: 6, Tails 2, Theta MAP: 0.700000
Toss no 9 
 Heads: 7, Tails 2, Theta MAP: 0.727273
Toss no 10 
 Heads: 8, Tails 2, Theta MAP: 0.750000
Toss no 11 
 Heads: 9, Tails 2, Theta MAP: 0.769231
Toss no 12 
 Heads: 10, Tails 2, Theta MAP: 0.785714
Toss no 13 
 Heads: 11, Tails 2, Theta MAP: 0.800000
Toss no 14 
 Heads: 12, Tails 2, Theta MAP: 0.812500
Toss no 15 
 Heads: 13, Tails 2, Theta MAP: 0.823529
Toss no 16 
 Heads: 14, Tails 2, Theta MAP: 0.833333
Toss no 17 
 Heads: 14, Tails 3, Theta MAP: 0.789474
Toss no 18 
 Heads: 15, Tails 3, Theta MAP: 0.800000
Toss no 19 
 Heads: 16, Tails 3, Theta MAP: 0.809524
Toss no 20 
 

<div style="background-color:#F9F2EB; text-align:left; padding: 10px;">
Your dataset description here: ... 